<?php
/**
 * 
 *
 * @package      Advanced Custom Fields (ACF) Custom Blocks 
 * 
 *                  Custom Post Type: "Great Lakes Chronicle"
 *                  Custom Fields\Field Group name for field definitions: "chronicle"
 *                  Custom Fields block name: "chronicle_view"
 *                  Displays current chronicle issue via the top menu choice Resources/Current Great Lakes Chronicle.
 *                  This code does NOT display Chronicle from the Homepage "e-News" or via the "Great Lakes Chronicle Archive"
 *                  Those reports are generated by the WordPress Custom Post Type templates (see content-single-chronicle.php and archive-chronicle.php)
 *                  URL: homepage url/chronicle_view/ 
 * 
 * @author       Patrick Moriarty
 * @since        1.0.0
 * @license      GPL-2.0+
 
 * 
 * This routine displays records for the custom post type (CPT) listed above.  Custom Post types are defined under the 'CPT UI' menu choice in the WordPress admin 
 * menu.  The fields for the CPT that this routine reads in and outputs are defined under the Custom Fields\Field Group name for field definitions (listed above). 
 * This Custom Fields\Field Group is also where the fields are linked to the CPT. There is a menu choice for the custom post type in the WordPress Admin menu, where
 * you can go to add records (or posts).  
 * 
 * This code is registered and linked to the block name (listed above) in the function pm_register_blocks().  To display the records for this CPT on a page, you
 * simply add the block to a page with the WordPress block editor. 
 * 
 * 
**/



?>

<style>

.column {
  float: left;
  width: 75%;
  column-width:100%;
}

.column_right {
  float: left;
  width: 20%;
  column-width:100%;
  padding-top: 350px;
  padding-left: 10px;
}


.center {
   display: block;
    margin-left: auto;
    margin-right: auto;
    width: 75%;
  }

  .alignfull {
	margin: 32px calc(50% - 50vw);
	max-width: 100vw;
	width: 100vw;
}



/* Responsive layout - makes the two columns stack on top of each other instead of next to each other on screens that are smaller than 600 px */

@media screen and (max-width: 482px) {
  .column {
    width: 100%;
  }
}
@media screen and (max-width: 482px) {
  .column_right {
    width: 100%;
  }
}

@media only screen and (min-width: 482px) {
	:root {
		--responsive--aligndefault-width: min(calc(100vw - 4 * var(--global--spacing-horizontal)), 1110px);
	}
}
@media only screen and (min-width: 822px) {
	:root {
		--responsive--aligndefault-width: min(calc(100vw - 8 * var(--global--spacing-horizontal)), 1110px);
	}
}
</style>

<?php



   //  Questions and Answers


   $args2 = array(
   'post_type'          => 'chronicle',
   'posts_per_page'	    => -1,
   'meta_key'			=> 'volume_issue',
   'orderby'			=> 'meta_value',
   'order'				=> 'DESC'
);



   /* The 2nd Query */
   $query2 = new WP_Query( $args2 );
    
if ($query2->have_posts())  {
?>


<article id="post-<?php echo $query2->post->ID; ?>" <?php post_class(); ?>>

<header class="entry-header alignwide">
		<?php the_title( '<h1 class="entry-title">', '</h1>' ); ?>
		<?php twenty_twenty_one_post_thumbnail(); ?>
	</header><!-- .entry-header -->

	<h1 style="text-align:center" >Great Lakes Chronicle</h1><br>

		<?php
		//the_content();
?>
		<!-- Let's show our custom fields here -->

	<p> <?php echo get_field('month', $query2->post->ID); ?></p>
	<p style="text-align:right"> <?php echo "Volume: ".get_field('volume', $query2->post->ID).", Issue: ". get_field('issue', $query2->post->ID); ?></p>

	<div class="column" >
	
	<?php chronicle_displayfields($query2->post->ID); ?>

	</div>
	<div class="column_right" >
		<a href="<?php echo site_url('chronicle'); ?>" target="_self">
			Chronicle Archive</a><br>
	</div>

<?php
	
// echo '<pre>';
//     print_r( $term->name );
// 	print_r( $term);
// echo '</pre>';
// die;		

?>




</article><!-- #post-<?php $query2->post->ID; ?> -->



<?php

}  // Big End If
?>






